services:
  dns:
    networks:
      amnezia-dns:
        ipv4_address: 172.29.172.153

  socks5proxy:
    environment:
      SOCKS5_COMPAT_CONFIG: /compat/3proxy.cfg
    volumes:
      - /srv/amnezia/socks5proxy/conf:/compat:ro

  awg:
    environment:
      AWG_COMPAT_STATE_DIR: /compat/awg
    networks:
      - amnezia-dns
    volumes:
      - /srv/amnezia/awg:/compat/awg

  xray:
    environment:
      XRAY_COMPAT_STATE_DIR: /compat/xray
    networks:
      - amnezia-dns
    volumes:
      - /srv/amnezia/xray:/compat/xray

networks:
  amnezia-dns:
    name: amnezia-dns-net
    external: true
