domain-insecure: "coin."
domain-insecure: "emc."
domain-insecure: "lib."
domain-insecure: "bazar."
domain-insecure: "enum."

stub-zone:
   name: "coin."
   stub-host: seed1.emercoin.com
   stub-host: seed2.emercoin.com
   stub-first: yes

stub-zone:
   name: "emc."
   stub-host: seed1.emercoin.com
   stub-host: seed2.emercoin.com
   stub-first: yes

stub-zone:
   name: "lib."
   stub-host: seed1.emercoin.com
   stub-host: seed2.emercoin.com
   stub-first: yes

stub-zone:
   name: "bazar."
   stub-host: seed1.emercoin.com
   stub-host: seed2.emercoin.com
   stub-first: yes

stub-zone:
   name: "enum."
   stub-host: seed1.emercoin.com
   stub-host: seed2.emercoin.com
   stub-first: yes

forward-zone:
   name: "."
   forward-tls-upstream: yes
   forward-first: yes

   forward-addr: 1.1.1.1@853#cloudflare-dns.com
   forward-addr: 1.0.0.1@853#cloudflare-dns.com

   forward-addr: 9.9.9.9@853#dns.quad9.net
   forward-addr: 149.112.112.112@853#dns.quad9.net

   forward-addr: 8.8.8.8@853#dns.google
   forward-addr: 8.8.4.4@853#dns.google
