[Interface]
PrivateKey = __AWG_SERVER_PRIVATE_KEY__
Address = __AWG_SERVER_ADDRESS__
ListenPort = __AWG_LISTEN_PORT__
Jc = __AWG_JUNK_PACKET_COUNT__
Jmin = __AWG_JUNK_PACKET_MIN_SIZE__
Jmax = __AWG_JUNK_PACKET_MAX_SIZE__
S1 = __AWG_INIT_PACKET_JUNK_SIZE__
S2 = __AWG_RESPONSE_PACKET_JUNK_SIZE__
S3 = __AWG_COOKIE_REPLY_PACKET_JUNK_SIZE__
S4 = __AWG_TRANSPORT_PACKET_JUNK_SIZE__
H1 = __AWG_INIT_PACKET_MAGIC_HEADER__
H2 = __AWG_RESPONSE_PACKET_MAGIC_HEADER__
H3 = __AWG_UNDERLOAD_PACKET_MAGIC_HEADER__
H4 = __AWG_TRANSPORT_PACKET_MAGIC_HEADER__

__AWG_PEERS_BLOCK__
