[Interface]
Address = __AWG_CLIENT_ADDRESS__
DNS = __AWG_PRIMARY_DNS__, __AWG_SECONDARY_DNS__
PrivateKey = __AWG_CLIENT_PRIVATE_KEY__
Jc = __AWG_JUNK_PACKET_COUNT__
Jmin = __AWG_JUNK_PACKET_MIN_SIZE__
Jmax = __AWG_JUNK_PACKET_MAX_SIZE__
S1 = __AWG_INIT_PACKET_JUNK_SIZE__
S2 = __AWG_RESPONSE_PACKET_JUNK_SIZE__
S3 = __AWG_COOKIE_REPLY_PACKET_JUNK_SIZE__
S4 = __AWG_TRANSPORT_PACKET_JUNK_SIZE__
H1 = __AWG_INIT_PACKET_MAGIC_HEADER__
H2 = __AWG_RESPONSE_PACKET_MAGIC_HEADER__
H3 = __AWG_UNDERLOAD_PACKET_MAGIC_HEADER__
H4 = __AWG_TRANSPORT_PACKET_MAGIC_HEADER__
I1 = __AWG_SPECIAL_JUNK_1__
I2 = __AWG_SPECIAL_JUNK_2__
I3 = __AWG_SPECIAL_JUNK_3__
I4 = __AWG_SPECIAL_JUNK_4__
I5 = __AWG_SPECIAL_JUNK_5__

[Peer]
PublicKey = __AWG_SERVER_PUBLIC_KEY__
PresharedKey = __AWG_PRESHARED_KEY__
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = __AWG_SERVER_HOST__:__AWG_PUBLISHED_PORT__
PersistentKeepalive = 25
